# Generated by Django 5.2.17 on 2026-09-17 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('priority', models.PositiveIntegerField(default=5)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['deadline', '-priority'],
                'indexes': [models.Index(fields=['owner'], name='projects_owner_i_c299b3_idx'), models.Index(fields=['status'], name='projects_status_6303d7_idx'), models.Index(fields=['deadline'], name='projects_deadlin_ebe3da_idx'), models.Index(fields=['owner', 'status'], name='projects_owner_i_597fe2_idx'), models.Index(fields=['owner', 'deadline'], name='projects_owner_i_d110c0_idx')],
            },
        ),
    ]
