# Generated by Django 5.2.17 on 2026-09-17 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='TODO', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Priority rank from 1 (lowest) to 10 (highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Progress from 0% to 100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_seconds', models.PositiveIntegerField(default=3600, help_text='Estimated completion time in seconds')),
                ('actual_seconds', models.PositiveIntegerField(default=0, help_text='Cached aggregate of closed time entries in seconds')),
                ('deadline', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(db_index=True, default='General', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=128, null=True)),
                ('recurrence_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.project')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['deadline', '-priority'],
                'indexes': [models.Index(fields=['project'], name='tasks_project_f1bd77_idx'), models.Index(fields=['assigned_to'], name='tasks_assigne_00feb5_idx'), models.Index(fields=['created_by'], name='tasks_created_816ff3_idx'), models.Index(fields=['status'], name='tasks_status_031d4c_idx'), models.Index(fields=['deadline'], name='tasks_deadlin_7f16a6_idx'), models.Index(fields=['assigned_to', 'status'], name='tasks_assigne_801c9d_idx'), models.Index(fields=['assigned_to', 'deadline'], name='tasks_assigne_a5d071_idx'), models.Index(fields=['project', 'status'], name='tasks_project_fe19a5_idx')],
            },
        ),
    ]
