# Generated by Django 5.2.17 on 2026-09-17 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('TASK', 'Task'), ('MEETING', 'Meeting'), ('FOCUS', 'Focus Session'), ('BREAK', 'Break'), ('PERSONAL', 'Personal')], db_index=True, default='TASK', max_length=20)),
                ('source', models.CharField(choices=[('INTERNAL', 'Internal'), ('AI', 'AI Scheduled'), ('GOOGLE', 'Google Calendar'), ('OUTLOOK', 'Outlook Calendar')], default='INTERNAL', max_length=20)),
                ('external_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('recurrence_rule', models.CharField(blank=True, max_length=128, null=True)),
                ('recurrence_until', models.DateTimeField(blank=True, null=True)),
                ('reminder_minutes', models.PositiveIntegerField(blank=True, default=15, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_url', models.URLField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_events', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule_events',
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['user', 'start_at'], name='schedule_ev_user_id_1f5192_idx'), models.Index(fields=['user', 'end_at'], name='schedule_ev_user_id_e5b765_idx'), models.Index(fields=['user', 'start_at', 'end_at'], name='schedule_ev_user_id_a7e244_idx'), models.Index(fields=['task'], name='schedule_ev_task_id_339fb0_idx'), models.Index(fields=['external_provider', 'external_id'], name='schedule_ev_externa_1f319c_idx')],
            },
        ),
    ]
