# Generated by Django 5.2.17 on 2026-09-17 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('SCHEDULE_RECOMMENDATION', 'Schedule Recommendation'), ('TIME_ALLOCATION', 'Time Allocation'), ('PRODUCTIVITY_PREDICTION', 'Productivity Prediction'), ('ANOMALY', 'Anomaly'), ('TASK_CLASSIFICATION', 'Task Classification'), ('PRIORITY_RECOMMENDATION', 'Priority Recommendation'), ('FOCUS_RECOMMENDATION', 'Focus Recommendation'), ('PERSONALIZED_RECOMMENDATION', 'Personalized Recommendation'), ('NLP_RESULT', 'NLP Result')], db_index=True, default='PERSONALIZED_RECOMMENDATION', max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('APPLIED', 'Applied'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=64, null=True)),
                ('model_version', models.CharField(blank=True, max_length=32, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=32, null=True)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to='scheduling.scheduleevent')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='ai_insights_user_id_5f48a9_idx'), models.Index(fields=['user', 'insight_type'], name='ai_insights_user_id_1e6be5_idx'), models.Index(fields=['generated_at'], name='ai_insights_generat_55fbee_idx')],
            },
        ),
    ]
