# Generated by Django 5.2.17 on 2026-09-17 17:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Materialized total elapsed seconds calculated server-side')),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('IMPORTED', 'Imported')], default='MANUAL', max_length=20)),
                ('tracking_method', models.CharField(choices=[('TIMER', 'Timer'), ('DESKTOP', 'Desktop'), ('BROWSER', 'Browser'), ('MOBILE', 'Mobile'), ('SYSTEM', 'System')], default='TIMER', max_length=20)),
                ('activity_type', models.CharField(default='Work', max_length=64)),
                ('application_name', models.CharField(blank=True, max_length=128, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=128, null=True)),
                ('productivity_category', models.CharField(choices=[('PRODUCTIVE', 'Productive'), ('NEUTRAL', 'Neutral'), ('DISTRACTION', 'Distraction'), ('UNKNOWN', 'Unknown')], db_index=True, default='PRODUCTIVE', max_length=20)),
                ('classification_confidence', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_entries',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='time_entrie_user_id_012afe_idx'), models.Index(fields=['task', 'started_at'], name='time_entrie_task_id_39e9e7_idx'), models.Index(fields=['project', 'started_at'], name='time_entrie_project_f9922b_idx'), models.Index(fields=['user', 'productivity_category', 'started_at'], name='time_entrie_user_id_a6dcf1_idx'), models.Index(fields=['status'], name='time_entrie_status_22f49a_idx')],
            },
        ),
    ]
