# Generated by Django 5.2.17 on 2026-09-17 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('productive_seconds', models.PositiveIntegerField(default=0)),
                ('nonproductive_seconds', models.PositiveIntegerField(default=0)),
                ('neutral_seconds', models.PositiveIntegerField(default=0)),
                ('tracked_seconds', models.PositiveIntegerField(default=0)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('focus_seconds', models.PositiveIntegerField(default=0)),
                ('meeting_seconds', models.PositiveIntegerField(default=0)),
                ('break_seconds', models.PositiveIntegerField(default=0)),
                ('tasks_total', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_overdue', models.PositiveIntegerField(default=0)),
                ('scheduled_seconds', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('focus_rate', models.FloatField(default=0.0)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('efficiency_score', models.FloatField(default=0.0)),
                ('anomaly_count', models.PositiveIntegerField(default=0)),
                ('peak_start_time', models.TimeField(blank=True, null=True)),
                ('peak_end_time', models.TimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_productivity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productivity_daily',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='productivit_user_id_445b1c_idx'), models.Index(fields=['date'], name='productivit_date_edf760_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_productivity')],
            },
        ),
    ]
