# Generated by Django 5.2.17 on 2026-09-17 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TASK_DEADLINE', 'Task Deadline'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_OVERDUE', 'Task Overdue'), ('MEETING_REMINDER', 'Meeting Reminder'), ('FOCUS_SESSION_REMINDER', 'Focus Session Reminder'), ('BREAK_REMINDER', 'Break Reminder'), ('DAILY_SUMMARY', 'Daily Summary'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('PRODUCTIVITY_ALERT', 'Productivity Alert'), ('AI_RECOMMENDATION', 'AI Recommendation'), ('SCHEDULE_CHANGED', 'Schedule Changed'), ('SECURITY_ALERT', 'Security Alert')], db_index=True, default='TASK_DEADLINE', max_length=40)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email')], db_index=True, default='IN_APP', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('READ', 'Read'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(choices=[('INTERNAL', 'Internal'), ('BREVO', 'Brevo')], default='INTERNAL', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('provider_template_id', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_event', models.CharField(blank=True, max_length=64, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='scheduling.scheduleevent')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['user', 'delivery_status'], name='notificatio_user_id_a4b1d6_idx'), models.Index(fields=['scheduled_for', 'delivery_status'], name='notificatio_schedul_f5a332_idx'), models.Index(fields=['notification_type', 'channel'], name='notificatio_notific_1897f3_idx'), models.Index(fields=['provider_message_id'], name='notificatio_provide_2a32d9_idx')],
            },
        ),
    ]
