# Generated by Django 5.2.17 on 2026-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_DEADLINE', 'Task Deadline'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_OVERDUE', 'Task Overdue'), ('MEETING_REMINDER', 'Meeting Reminder'), ('FOCUS_SESSION_REMINDER', 'Focus Session Reminder'), ('BREAK_REMINDER', 'Break Reminder'), ('DAILY_SUMMARY', 'Daily Summary'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('PRODUCTIVITY_ALERT', 'Productivity Alert'), ('AI_RECOMMENDATION', 'AI Recommendation'), ('SCHEDULE_CHANGED', 'Schedule Changed'), ('SECURITY_ALERT', 'Security Alert')], db_index=True, default='TASK_DEADLINE', max_length=40),
        ),
    ]
